### ISSUE TITLE
Support Series

### ISSUE THREAD

**Issue by andresmijares** [andresmijares/react-calendar-multiday#7]
A serie feature is required, where multiple selected days can be passed as an object props, and user is able to change the series on their selection.

Ideally, a selected days props will be in the following format:

```javascript
const series : {
   1: [/**date**/, /**date**/, /**date**/],
   2: [/**date**/, /**date**/, /**date**/],
   3: [/**date**/, /**date**/, /**date**/],
}
```

This will store in the `Calendar` component state and will expose a single API to add or remove date from that specific serie as `handleSeries` which return the current series state copy and `currentSerie` to set a default on runtime.

Days logic will be kept the same.

**Comment by nachomazzara** [comment]
How are we going to handle the API for adding and removing? Are we going to keep `selectedDays` as it is and add a new prop called `channels`? 

Also, the Days logic will need to be modified in order to distinguish at least colors between each channel or between `not selected`, `selectedDays` and `currentEditingChannelDays`

**Comment by andresmijares** [comment]
The only different on the day component will be that it will receive the channel object, the rest should keep the same so we do not break the other cases.

the calendar component will expose a create, delete and chance between channels.

there is not notion of selectedDays when using channels, this mean we need to make all the calculations on the day coment taking advantage of the channel object.

**Comment by nachomazzara** [comment]
Should we need to mark as done, right?
